algoritmo "Aula 10"
// Função : Aula 10
// Autor : João Emanuel
// Data : 13/04/2021
// Seção de Declarações
var
l, c, f: inteiro
res: caractere
inicio
// Seção de Comandos
   repita
      F <- F * L
      L <- L - 1
   ate (L < 1)
escreval("O fatorial de",c," é igual a ",f)
fimalgoritmo

repita
   Escreva("Digite um numero ")
   leia(c)
   l <- c
   f <- 1
   Escreval("Deseja continuar? [S/N] ")
   leia(res)
ate (res = "N")
