algoritmo "Aula 10"
// Função : Aula 10
// Autor : João Emanuel
// Data : 13/04/2021
// Seção de Declarações
var
C,N, CDIV: inteiro
inicio
// Seção de Comandos
c <- 1
Escreva("Digite um numero ")
leia(n)
cdiv <- 0
repita
   se (N % C = 0) entao
      CDIV <- Cdiv + 1
   fimse
   c <- c + 1
ate (c > n)
se (CDIV = 2) entao
   escreval("O numero é primo")
senao
   Escreval("O numero não é primo")
fimse
fimalgoritmo
