algoritmo "Primeiro"
// Função : Testar o visualgv
// Autor : João Emanuel
// Data : 09/04/2021
// Seção de Declarações: A interfaçe é bem confusa, mas acredito que eu ja tenha indetificado algumas coias, essa seria a area de docstrings com comentarios
var
msg: caractere
inicio
// Seção de Comandos 
Escreval("Olá, Mundo!")
Escreval("Me livrei da maldição")
msg <- "Oi, sera que funciona?"
Escreval("Teste, ", msg)
fimalgoritmo
