algoritmo "Aula 09"
// Função : Aula 09
// Autor : João Emanuel
// Data : 13/04/2021
// Seção de Declarações
var
c, d: real
l, cc: inteiro
inicio
// Seção de Comandos
Escreval("Quantas vezes você quer converter?")
leia(cc)
enquanto (l <= cc - 1) faca
   escreval("Digite o valor em reais")
   leia(c)
   d <- c / 5.70
   Escreval(c:5:2," Reais convertido em Dolares é igual a",d:5:2)
   l <- l + 1
fimenquanto
fimalgoritmo
