algoritmo "Aula 07"
// Função :Aula 07
// Autor :João Emanuel
// Data : 12/04/2021
// Seção de Declarações
var
ano, nas, id: inteiro
inicio
// Seção de Comandos
Escreva("Ano atual ")
leia(ano)
escreva("Ano do seu nascimento ")
leia(nas)
id <- ano - nas
se (id > 18) entao
   escreval("Sua idade é de",id," anos portanto você esta apito a retirar a carteira")
senao
     escreva("Sua idade é de",id," anos portanto você não esta apito a retirar a carteira")
FIMSE
fimalgoritmo

